server:
  port: 8001

mybatis:
  config-location: "classpath:mybatis/mybatis.cfg.xml"        # mybatis配置文件所在路径
  mapper-locations:
    - "classpath:mapper/**/*.xml"                     # mapper映射文件
  type-aliases-package: com.liujia.entity            # 别名类所在包

#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://120.79.96.251:5432/hdsc_db
#    username: hdsc_user_cha
#    password: gsYWNfe4
#    name: druid

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.47.9:3306/bwc
    username: test
    password: test
    type: com.alibaba.druid.pool.DruidDataSource


