
spring:
  profiles:
    active: dev

---
server:
  port: 8083
spring:
  profiles: dev


---

server:
  port: 8084
spring:
  profiles: prod  #指定属于哪个环境
---


mybatis:
  config-location: "classpath:mybatis/mybatis.cfg.xml"        # mybatis配置文件所在路径
  mapper-locations:
    - "classpath:mapper/**/*.xml"                     # mapper映射文件
  type-aliases-package: com.liujia.entity            # 别名类所在包


#logging:
#  pattern:
#    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'
#    file: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n'
#  level:
#    root: trace
#    com:
#      liujia:
#        mapper: debug
#  file: D:/springboot.log

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com:
      liujia:
        mapper: debug


#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://120.79.96.251:5432/hdsc_db
#    username: hdsc_user_cha
#    password: gsYWNfe4
#    name: druid

debug: true   #查看自动配置的类哪些生效

# 禁用缓存
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.96.47.9:3306/bwc?useSSL=false
    username: test
    password: test
    type: com.alibaba.druid.pool.DruidDataSource
    schema:
      - classpath:test.sql
    initialization-mode: ALWAYS  #初始化执行sql脚本
    initial-size: 5  # 初始化大小
    min-idle: 5  # 最小
    max-active: 100  # 最大
    max-wait: 60000  # 配置获取连接等待超时的时间
    time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
    validationQuery: select 'x'
    test-while-idle: true  # 当连接空闲时，是否执行连接测试
    test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
    test-on-return: false  # 在连接归还到连接池时是否测试该连接
    filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=false
    # 合并多个DruidDataSource的监控数据
    #use-global-data-source-stat: true
    #WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
    web-stat-filter:
      enabled: true #是否启用StatFilter默认值true
      url-pattern: /*
      exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
      session-stat-enable: true
      session-stat-max-count: 10
    #StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
    stat-view-servlet:
      enabled: true #是否启用StatViewServlet默认值true
      url-pattern: /druid/*
      reset-enable: true
      login-username: admin
      login-password: admin

  thymeleaf:
    cache: false


name: zhangsan \n lisi       #字符串，和''一样
name1: "zhangsan \n lisi"    #双引号不会转义，\n 为换行
name2: 'zhangsan \n lisi'    #单引号会转义，  \n 输出\n

#friends:
#  lastname: zhangsan     换行写法
#  age: 18

#friends: {lastname: zhangsan,age: 18}

#dayofweek:
#  week:
#  - monday
#  - tuesday
#  - wednesday
#  - thursday
#  - friday
#  - saturday
#  - sunday

dayofweek:
  week: [monday,tuesday,wednesday,thursday,friday,saturday,sunday]

#person:
#  lastName: 王八蛋
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1,k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 12